<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net8.0-windows</TargetFramework>
      <Nullable>enable</Nullable>
      <UseWPF>true</UseWPF>
	  <Platforms>AnyCPU</Platforms>
      <ImplicitUsings>enable</ImplicitUsings>
	  <!-- 如需发包可开启 -->
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

	  <!-- NuGet 基本信息 -->
	  <PackageId>PixMetron.Controls.ImageViewport</PackageId>
	  <!-- 用 SemVer，预发布如 1.1.0-beta.1 -->
	  <Version>0.1.0-beta.0</Version>
	  <Authors>PixMetron</Authors>
	  <Description>A WPF image viewport control with extensible facade architecture, multi-layered surface rendering, coordinate transformations, and composable input handling for pan/zoom and custom interactions.</Description>
	  <PackageTags>WPF;Viewport;Imaging</PackageTags>

	  <!-- 可见性与合规 -->
	  <PackageProjectUrl>https://github.com/PixMetron</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/PixMetron/ImageViewport</RepositoryUrl>
	  <RepositoryType>git</RepositoryType>
	  <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>

	  <!-- README / 图标（会显示在 nuget.org 包页） -->
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <!--<PackageIcon>docs\icon.png</PackageIcon>-->

	  <!-- 文档与 SourceLink（推荐） -->
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
